### ISSUE TITLE
nsq/monitoring: serve metrics to prometheus

### ISSUE THREAD

**Issue by mgenov** [nsqio/helm-chart#3]
It would be nice if chart allows monitoring value to be set for exposing of nsq metrics to prometheus. 
For example, the https://github.com/lovoo/nsq_exporter could be imported as container in the statefulset when metrics options is set. 

Here is an example how this is done in mongodb:

```yaml
    metrics:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mongodb-exporter        
        tag: 0.31.2-debian-10-r0
        pullPolicy: IfNotPresent     
```
